Repository reilabs/lampe, pull requests merged in 2025-09, with the labels that each got.

#190 Transfer the delaborator to the new syntax
  Lampe/Lampe.lean
  Lampe/Lampe/Data/Meta.lean
  Lampe/Lampe/Syntax.lean
  Lampe/Lampe/Syntax/Delab.lean
  Lampe/Lampe/Syntax/Rules.lean
  Lampe/Lampe/Syntax/Utils.lean
  Lampe/Lampe/Tactic/EnvSubsetSolver.lean
  Lampe/Lampe/Tactic/SL.lean
  Lampe/Lampe/Tactic/Steps.lean
  Lampe/Lampe/Tactic/Traits.lean
  Lampe/Tests/Syntax.lean
  testing/TestDep/testing/GitDepWithLampe/lampe/GitDepWithLampe-0.0.0/Extracted/Lib.lean
  testing/TestDep/testing/GitDepWithLampeV1/lampe/GitDepWithLampe-1.0.0/Extracted/Lib.lean
  testing/TestDep/testing/GitDepWithLampeV2/lampe/GitDepWithLampe-2.0.0/Extracted/Lib.lean
  testing/TestDep/testing/LocalDepWithLampe/lampe/LocalDepWithLampe-0.0.0/Extracted/Lib.lean
  testing/TestDep/testing/LocalDepWithLampeV1/lampe/LocalDepWithLampe-1.0.0/Extracted/Lib.lean
  testing/TestDep/testing/LocalDepWithLampeV2/lampe/LocalDepWithLampe-2.0.0/Extracted/Lib.lean
Labels: tech debt

#175 add some error handling to steps tactic
  Lampe/Lampe/Semantics/Env.lean
  Lampe/Lampe/Tactic/Steps.lean
  Lampe/Lampe/Tp.lean
  Lampe/Tests/Envs.lean
  Lampe/Tests/Errors.lean
  Lampe/Tests/Negatives.lean
  Lampe/Tests/Syntax.lean
  testing/Merkle/lampe/Merkle-0.0.0/Spec.lean
  testing/MerkleFromScratch/user_files/Spec.lean
Labels: enhancement

#200 Better tactics
  Lampe/Lampe.lean
  Lampe/Lampe/Builtin/Basic.lean
  Lampe/Lampe/Hoare/Builtins.lean
  Lampe/Lampe/Hoare/SepTotal.lean
  Lampe/Lampe/Lens.lean
  Lampe/Lampe/Tactic/EnvSubsetSolver.lean
  Lampe/Lampe/Tactic/SL.lean
  Lampe/Lampe/Tactic/SL/Init.lean
  Lampe/Lampe/Tactic/SL/Term.lean
  Lampe/Lampe/Tactic/SLNorm.lean
  Lampe/Lampe/Tactic/Steps.lean
  Lampe/Tests/Envs.lean
  Lampe/Tests/Errors.lean
  Lampe/Tests/LenBuiltin.lean
  Lampe/Tests/Syntax.lean
  stdlib/lampe/Stdlib/Option.lean
  stdlib/lampe/Stdlib/Slice.lean
  testing/Merkle/lampe/Merkle-0.0.0/Spec.lean
  testing/MerkleFromScratch/user_files/Spec.lean
Labels: enhancement

#202 Fix operator-trait naming
  src/lean/generator.rs
  stdlib/lampe/std-1.0.0-beta.11/Extracted/Array/CheckShuffle.lean
  stdlib/lampe/std-1.0.0-beta.11/Extracted/Array/Mod.lean
  stdlib/lampe/std-1.0.0-beta.11/Extracted/Cmp.lean
  stdlib/lampe/std-1.0.0-beta.11/Extracted/Collections/BoundedVec.lean
  stdlib/lampe/std-1.0.0-beta.11/Extracted/Collections/Map.lean
  stdlib/lampe/std-1.0.0-beta.11/Extracted/Collections/Umap.lean
  stdlib/lampe/std-1.0.0-beta.11/Extracted/Collections/Vec.lean
  stdlib/lampe/std-1.0.0-beta.11/Extracted/EmbeddedCurveOps.lean
  stdlib/lampe/std-1.0.0-beta.11/Extracted/Field/Bn254.lean
  stdlib/lampe/std-1.0.0-beta.11/Extracted/Field/Mod.lean
  stdlib/lampe/std-1.0.0-beta.11/Extracted/Hash/Mod.lean
  stdlib/lampe/std-1.0.0-beta.11/Extracted/Option.lean
  stdlib/lampe/std-1.0.0-beta.11/Extracted/Slice.lean
Labels: bug

#203 Shuffle check
  Lampe/Lampe/Builtin/Arith.lean
  stdlib/lampe/Stdlib/Array/CheckShuffle.lean
  stdlib/lampe/Stdlib/Array/Mod.lean
Labels: enhancement

#211 Add the remaining theorems for `Option`
  Lampe/Lampe/Hoare/SepTotal.lean
  Lampe/Lampe/Tactic/SL.lean
  Lampe/Lampe/Tactic/SL/Term.lean
  Lampe/Lampe/Tactic/Steps.lean
  docs/Extracted Project Structure.md
  docs/Tips for Proving.md
  stdlib/lampe/Stdlib/Array/Mod.lean
  stdlib/lampe/Stdlib/Option.lean
  stdlib/lampe/Stdlib/Slice.lean
Labels: enhancement
